GET http://localhost:8080/ HTTP/1.1

###

GET http://localhost:8080/register HTTP/1.1

###

GET http://localhost:8080/start HTTP/1.1

###

GET http://localhost:8080/command/forward/100 HTTP/1.1

###

GET http://localhost:8080/command/left/90 HTTP/1.1

###

GET http://localhost:8080/command/stop/ HTTP/1.1

###

GET http://localhost:8080/finished HTTP/1.1